const fs = require('fs');
const path = require('path');

const content = fs.readFileSync('./src/astronomy/theories/elp2000/elp2000Data.ts', 'utf-8');
const lines = content.split('\n').filter(line => !line.startsWith('//'));
const jsonStr = lines.join('').replace('export const elp2000Data = ', '').trim().replace(/;$/, '');
const elpData = JSON.parse(jsonStr);

function packArray(arr, keys) {
    const buffer = new ArrayBuffer(arr.length * keys.length * 8);
    const view = new Float64Array(buffer);
    let i = 0;
    for (const item of arr) {
        for (const key of keys) {
            // Some objects might be missing B, default to 0
            view[i++] = item[key] !== undefined ? item[key] : 0;
        }
    }
    return Buffer.from(buffer).toString('base64');
}

const keysMain = ['i1', 'i2', 'i3', 'i4', 'A', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6'];
const keysNonPlanetary = ['i1', 'i2', 'i3', 'i4', 'i5', 'phi', 'A', 'B'];
const keysPlanetary = ['i1', 'i2', 'i3', 'i4', 'i5', 'i6', 'i7', 'i8', 'i9', 'i10', 'i11', 'phi', 'A', 'B'];

let output = `// Auto-generated by scripts/pack-elp2000.cjs
// Do not edit manually.

export function decodeBase64Flat(base64: string): Float64Array {
  const binaryString = typeof atob === 'function' ? atob(base64) : Buffer.from(base64, 'base64').toString('binary');
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return new Float64Array(bytes.buffer);
}

// Flat structured proxy for the previous object-based interface.
class PackedTermProxy {
  constructor(private data: Float64Array, private stride: number, private keys: string[]) {}
  
  get length() { return this.data.length / this.stride; }
  
  // Creates a virtual object for index i.
  // Note: For optimal performance, the evaluate loop should be rewritten
  // to just read from the Float64Array directly instead of creating objects.
  // But for backwards compatibility with the existing code:
  [Symbol.iterator]() {
    let index = 0;
    const len = this.length;
    const self = this;
    return {
      next() {
        if (index < len) {
          const obj: any = {};
          for (let k = 0; k < self.stride; k++) {
            obj[self.keys[k]] = self.data[index * self.stride + k];
          }
          index++;
          return { value: obj, done: false };
        }
        return { done: true, value: undefined };
      }
    };
  }

  // To support data[i] indexing
  [index: number]: any;
}

function createProxy(base64: string, keys: string[]) {
  const data = decodeBase64Flat(base64);
  const proxy = new PackedTermProxy(data, keys.length, keys);
  // Add indexed access
  for (let i = 0; i < proxy.length; i++) {
    Object.defineProperty(proxy, i, {
      get: () => {
        const obj: any = {};
        for (let k = 0; k < keys.length; k++) {
          obj[keys[k]] = data[i * keys.length + k];
        }
        return obj;
      }
    });
  }
  return proxy;
}

const keysMain = ['i1', 'i2', 'i3', 'i4', 'A', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6'];
const keysNonPlanetary = ['i1', 'i2', 'i3', 'i4', 'i5', 'phi', 'A', 'B'];
const keysPlanetary = ['i1', 'i2', 'i3', 'i4', 'i5', 'i6', 'i7', 'i8', 'i9', 'i10', 'i11', 'phi', 'A', 'B'];

export const elp2000Data: Record<string, any> = {};
`;

for (const key of Object.keys(elpData)) {
    if (key === 'truncationArcSeconds' || key === 'truncationKilometers') {
        output += `elp2000Data['${key}'] = ${elpData[key]};\n`;
        continue;
    }
    
    let keys;
    let typeName;
    if (key.match(/ELP0[123]/)) {
        keys = keysMain;
        typeName = 'keysMain';
    } else if (key.match(/ELP(0[4-9]|2[2-9]|3[0-6])/)) {
        keys = keysNonPlanetary;
        typeName = 'keysNonPlanetary';
    } else {
        keys = keysPlanetary;
        typeName = 'keysPlanetary';
    }

    const base64 = packArray(elpData[key], keys);
    console.log(`Packed ${key}: ${elpData[key].length} terms -> ${base64.length} chars`);
    
    output += `elp2000Data['${key}'] = createProxy("${base64}", ${typeName});\n`;
}

const outPath = path.join(__dirname, '../src/astronomy/theories/elp2000/elp2000Packed.ts');
fs.writeFileSync(outPath, output);
console.log(`Successfully generated ${outPath}`);
