import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// We'll dynamically import the compiled or raw coefficient files.
// Assuming we run this with `npx tsx` or `ts-node` so we can import .ts files.
import * as VSOP87 from '../src/astronomy/theories/vsop87/vsop87Coefficients.js';

// If ELP2000 is also structured similarly, you could import it here.
// import * as ELP2000 from '../src/astronomy/theories/elp2000/elp2000Coefficients.js';

function encodeSeries(series: { A: Float64Array, B: Float64Array, C: Float64Array }): string {
    const len = series.A.length;
    // 3 floats per term, 8 bytes per Float64
    const buffer = new ArrayBuffer(len * 3 * 8);
    const view = new Float64Array(buffer);
    for (let i = 0; i < len; i++) {
        view[i * 3]     = series.A[i];
        view[i * 3 + 1] = series.B[i];
        view[i * 3 + 2] = series.C[i];
    }
    return Buffer.from(buffer).toString('base64');
}

function generatePackedFile() {
    const exportsToEncode = [
        'L0', 'L1', 'L2', 'L3', 'L4', 'L5',
        'B0', 'B1', 'B2', 'B3', 'B4', 'B5',
        'R0', 'R1', 'R2', 'R3', 'R4', 'R5'
    ] as const;

    let output = `// Auto-generated by scripts/pack-coefficients.ts
// Do not edit manually.

export interface ParallelSeries {
  A: Float64Array;
  B: Float64Array;
  C: Float64Array;
}

/**
 * Instantly converts a Base64 string into a ParallelSeries of Float64Arrays.
 * Bypasses V8 AST array parsing, reducing TTI significantly.
 */
export function decodeBase64Series(base64: string): ParallelSeries {
  // Use atob if in browser, or Buffer in Node for compatibility
  const binaryString = typeof atob === 'function' ? atob(base64) : Buffer.from(base64, 'base64').toString('binary');
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  
  const interleaved = new Float64Array(bytes.buffer);
  const terms = interleaved.length / 3;
  
  const A = new Float64Array(terms);
  const B = new Float64Array(terms);
  const C = new Float64Array(terms);
  
  for (let i = 0; i < terms; i++) {
    A[i] = interleaved[i * 3];
    B[i] = interleaved[i * 3 + 1];
    C[i] = interleaved[i * 3 + 2];
  }
  
  return { A, B, C };
}

`;

    for (const key of exportsToEncode) {
        if (key in VSOP87) {
            const series = (VSOP87 as any)[key];
            const base64 = encodeSeries(series);
            console.log(`Packed ${key}: ${series.A.length} terms -> ${base64.length} chars (Base64)`);
            output += `export const ${key} = decodeBase64Series("${base64}");\n\n`;
        }
    }

    const outPath = path.join(__dirname, '../src/astronomy/theories/vsop87/vsop87Packed.ts');
    fs.writeFileSync(outPath, output);
    console.log(\`Successfully generated \${outPath}\`);
}

generatePackedFile();
